ProyectoWebApiHotelV1/Controllers/SesionController.cs
using ProyectoWebApiHotelV1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoWebApiHotelV1.Controllers
{
    public class SesionController : Controller
    {
        // GET: Sesion
        public ActionResult Index()
        {
            return View();
        }

        //----------------
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Usuarios objUser)
        {
            if (ModelState.IsValid)
            {
                using (ApiHotelContexto db = new ApiHotelContexto())
                {
                    var obj = db.Usuario.Where(a => a.Usuario.Equals(objUser.Usuario) 
                        && a.Contrasena.Equals(objUser.Contrasena)
                        ).FirstOrDefault();


                    if (obj != null && obj.Privilegio.Privilegio == "Administrador")
                    {

                        Session["IdUsuario"] = obj.IdUsuario.ToString();
                        Session["Usuario"] = obj.Usuario.ToString();
                        Session["Privilegio"] = obj.Privilegio.Privilegio.ToString();
                        return RedirectToAction("../Administrador");
                    }
                    else if (obj != null && obj.Privilegio.Privilegio == "Cliente")
                    { 
                        Session["IdUsuario"] = obj.IdUsuario.ToString();
                        Session["Usuario"] = obj.Usuario.ToString();
                        Session["Privilegio"] = obj.Privilegio.Privilegio.ToString();
                        return RedirectToAction("../Clientela");
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }
                    
                }
            }
            return View(objUser);
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("../Home/Index");
        }

        public ActionResult Administrador()
        {
            if (Session["IdUsuario"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        //------------------
    }
}

ProyectoWebApiHotelV1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top ">
        <div class="container">
            <div class="navbar-header">
                @*Html.ActionLink("HOTEL-WEB-API", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>*@
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, null)</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Iniciar sesión", "Index", "Sesion", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content panel-footer">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Edwin de León®</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>